src/service/programService.js
=> Issue #DP-543 feat: get aggregated counts of entire nomination table limit=0

src/helpers/programHelper.js, src/service/programService.js
Reverts Sunbird-Ed/program-service#43
=> Revert "Issue #dp-953 feat: Changes to Content Reports"

src/helpers/programHelper.js
Reverts Sunbird-Ed/program-service#62
=> Revert "Issue #DP-1057 fix: Total content contribution count"

src/helpers/programHelper.js
Reverts Sunbird-Ed/program-service#74
=> Revert "#dp-35 fix: showing corrections pending count in downloaded csv"

src/service/print/dataImporter.js, src/service/print/pdf.js
Using `acceptedContents` instead of `status` as the property being validated against for question approval status
=> DP-1612 Fix: Rejected questions inside print preview

src/package.json, src/routes/print.js, src/service/print/pdf.js, src/service/print/utils/docDefinition.js, src/service/print/utils/docStyles.js, src/test/service/printService.js
Also merge previously unmerged changes from `sprint-20` : 
- Print marks according to sum of approved questions
- Add Match The Following support
=> SB-23979: Support Comprehension Questions for Print Preview

src/package.json, src/routes/print.js, src/service/print/pdf.js, src/service/print/utils/docDefinition.js, src/service/print/utils/docStyles.js, src/test/service/printService.js
Reverts Sunbird-Ed/program-service#147
=> Revert "SB-23979: Support Comprehension Questions for Print Preview"

src/helpers/programHelper.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23188" title="SB-23188" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23188</a>   Enable contribution and review of Question set within a collection driven sourcing workflow
</td></table>
<br />
* …
=> Issue #sb-23188 feat: question editor integration

src/envVariables.js, src/service/programService.js
=> merge Release 3.8.0 into 3.9

src/helpers/programHelper.js, src/service/print/pdf.js, src/service/print/utils/docDefinition.js, src/test/service/printService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23980" title="SB-23980" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype" />SB-23980</a>  Enhance print preview service to include support for Images
</td></table>
<br />
* …
=> SB-23980: Print Preview- Image Support (Add baseUrl to media while fetching)

src/service/print/pdf.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23980" title="SB-23980" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10318&avatarType=issuetype" />SB-23980</a>  Enhance print preview service to include support for Images
</td></table>
<br />
* …
=> SB-23980: Fix line break on Comprehension question inside Print Preview

src/models/nomination.js, src/models/program.js, src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24732" title="SB-24732" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24732</a>  Projects are not listed according to the applied filters on All projects and My Projects tab.
</td></table>
<br />
* …
=> Issue #SB-24732 fix: content types filter not working

src/models/nomination.js, src/models/program.js, src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24732" title="SB-24732" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24732</a>  Projects are not listed according to the applied filters on All projects and My Projects tab.
</td></table>
<br />
* …
=> Issue #SB-24732 targetprimarycategorynames added

src/models/nomination.js, src/models/program.js, src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24732" title="SB-24732" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24732</a>  Projects are not listed according to the applied filters on All projects and My Projects tab.
</td></table>
<br />
* …
=> Issue #SB-24732 targetprimarycategorynames added #163

src/service/programService.js
=> Content type filter issue fix

auto_build_deploy
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24834" title="SB-24834" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24834</a>  CollectionEditor - Automatic publishing of NPM packages
</td></table>
<br />
* …
=> Issue #SB-24834 feat: Auto build and deploy

auto_build_deploy
=> updated jenkins file

src/helpers/programHelper.js, src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24467" title="SB-24467" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-24467</a>  Created sample Demo practice set content count is not getting updated in the view sample section.
</td></table>
<br /> …
=> Issue #SB-24467 fix: count is not coming in csv

src/sql-data/dummy.sql, src/test/service/printService.js, src/test/service/programServiceSpec.js
=> Issue #SB-000 fix: Added missing cols

src/envVariables.js, src/service/userService.js
=> Issue #SB-000 fix: security issue fix

README.md
=> Issue #SB-000 chore: add new steps to readme

src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25381" title="SB-25381" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25381</a>  Changes related to generalization of target collection
</td></table>
<br />
* …
=> Issue #SB-25381 feat: for target collection multiselect to work

src/helpers/programHelper.js, src/helpers/updateHierarchy.helper.js, src/service/bulkJobService.js, src/service/configurationService.js, src/service/programFeedService.js, src/service/programService.js, src/service/userProgramPreference.js
=> Issue #SB-000 fix: Copy collection log format issue fix

auto_build_deploy, src/helpers/programHelper.js, src/helpers/updateHierarchy.helper.js, src/service/bulkJobService.js, src/service/configurationService.js, src/service/programFeedService.js, src/service/programService.js, src/service/userProgramPreference.js
=> Issue #SB-000 merge Release 4.1.0 into 4.2.0

src/helpers/programHelper.js, src/models/program.js, src/routes/programRoutes.js, src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23256" title="SB-23256" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23256</a>  Enable "Seek assets NOT for target collections"
</td></table>
<br />
* Hardware …
=> Issue #sb-23256 fix: program service changes for target_type

src/helpers/programHelper.js, src/service/messageUtil.js, src/service/notificationService.js, src/service/programService.js, src/service/registryService.js, src/service/userService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25924" title="SB-25924" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25924</a>  Projects with "Invite Only" option for contributions - Part 1
</td></table>
<br /> …
=> Issue #SB-25924 feat: Projects with Invite Only option for contributions

src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23256" title="SB-23256" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23256</a>  Enable "Seek assets NOT for target collections"
</td></table>
<br />
* Hardware …
=> Issue #sb-23256 fix: copy collections if taret type is null

src/envVariables.js, src/service/notificationService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25924" title="SB-25924" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25924</a>  Projects with "Invite Only" option for contributions - Part 1
</td></table>
<br /> …
=> Updated env var SB-25924

src/package-lock.json, src/package.json, src/routes/print.js, src/service/print/docx.js, src/service/print/getdocxdata.js
=> Docx Implementation

src/app.js, src/envVariables.js, src/helpers/kafkaUtil.js, src/package-lock.json, src/package.json, src/routes/qumlBulkRoutes.js, src/service/kafkaQumlConsumerService.js, src/service/messageUtil.js, src/service/qumlBulkService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25750" title="SB-25750" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25750</a>  Bulk Question Upload API
</td></table>
<br />
We propose to implement a Bulk Upload API on the backend to enable uploading multiple (to the order of thousands) questions at once onto Diksha.
- [yes ] New feature (non-breaking change which adds functionality)
- [yes ] My code follows the style guidelines of this project
- [yes] I have performed a self-review of my own code
- [yes ] I have commented my code, particularly in hard-to-understand areas
- [yes] I have made corresponding changes to the …
=> Quml Bulk upload API as part of JIRA key-> SB-25750

src/qumlTestData.json, src/service/kafkaQumlConsumerService.js, src/service/qumlBulkService.js, src/test/service/qumlBulkService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25750" title="SB-25750" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25750</a>  Bulk Question Upload API
</td></table>
<br />
We propose to implement a Bulk Upload API on the backend to enable uploading multiple (to the order of thousands) questions at once onto Diksha.
- [yes] My code follows the style guidelines of this project
- [yes] I have performed a self-review of my own code
- [yes] I have commented my code, particularly in hard-to-understand areas
- [yes] I have made corresponding changes to the documentation
- [yes] My changes generate no new warnings
- [yes] I have added …
=> test case and corrections made as part of JIRA key-> SB-25750

src/helpers/programHelper.js, src/qumlTestData.json, src/routes/print.js, src/service/kafkaQumlConsumerService.js, src/service/print/dataImporter.js, src/service/print/docx.js, src/service/print/getdocxdata.js, src/service/qumlBulkService.js, src/test/service/qumlBulkService.js
=> SB-000 Merge Release 4.2.0 in to 4.3.0

src/package-lock.json, src/service/kafkaQumlConsumerService.js, src/service/qumlBulkService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25750" title="SB-25750" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25750</a>  Bulk Question Upload API
</td></table>
<br />
We propose to implement a Bulk Upload API on the backend to enable uploading multiple (to the order of thousands) questions at once onto Diksha.
- [yes] My code follows the style guidelines of this project
- [yes ] I have performed a self-review of my own code
- [yes] I have commented my code, particularly in hard-to-understand areas
- [yes] I have made corresponding changes to the documentation
- [yes] My changes generate no new warnings
- [yes] I have added …
=> bug fix made as per suggestions as part of JIRA key-> SB-25750

src/helpers/programHelper.js, src/package-lock.json, src/package.json, src/service/kafkaQumlConsumerService.js, src/service/qumlBulkService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25750" title="SB-25750" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25750</a>  Bulk Question Upload API
</td></table>
<br />
We propose to implement a Bulk Upload API on the backend to enable uploading multiple (to the order of thousands) questions at once.
- [yes] Bug fix (non-breaking change which fixes an issue)
- [yes] My code follows the style guidelines of this project
- [yes] I have performed a self-review of my own code
- [yes] I have commented my code, particularly in hard-to-understand areas
- [yes] I have made corresponding changes to the documentation
- [yes] My changes generate no new warnings
- [yes] I …
=> moving delay changed to 4.3 as part of JIRA key-> SB-25750

src/service/programService.js, src/service/telemetryService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24675" title="SB-24675" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-24675</a>  Generate AUDIT telemetry for program-service API's
</td></table>
<br />
* Hardware …
=> #SB-24675 feat: Generate AUDIT telemetry for program-service API's

src/service/programService.js
=> Issue #SB-000 fix: Tenant list API failing

src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26955" title="SB-26955" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-26955</a>  Users are not getting added to the sourcing org / default contribution org.
</td></table>
<br />
* Software …
=> Issue #sb-26955 fix: users not getting added to default contributor org

src/helpers/updateHierarchy.helper.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26692" title="SB-26692" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-26692</a>  VDN portal to use /api endpoint instead of /action/content/v3/hierarchy/:do_id
</td></table>
<br />
* Software …
=> SB-26692 VDN portal to use /api endpoint instead of /action/content/v3/hierarchy/:do_id

src/service/print/docx.js, src/service/print/getdocxdata.js
=> #SB-27302 - Accommodate different text formats and fonts in Sunbird Print Preview Service

src/service/programService.js
=> Issue #000 fix: programObj is undefined

src/envVariables.js, src/helpers/csv-helper-util.js, src/helpers/googleOauthHelper.js, src/middlewares/request.middleware.js, src/package.json, src/routes/qumlBulkRoutes.js, src/service/kafkaQumlConsumerService.js, src/service/messageUtil.js, src/service/qumlBulkService.js, src/validators/qumlBulkUploadValidators.js
<table>
<td>
</td></table>
<br />
* …
=> Issue #SB-23374 feat: Bulk Upload Questions

src/routes/qumlBulkRoutes.js, src/service/qumlBulkService.js
<table>
<td>
</td></table>
<br />
* …
=> Issue #SB-23374 feat : question bulk upload status API issue fixes

src/service/kafkaQumlConsumerService.js, src/service/qumlBulkService.js
<table>
<td>
</td></table>
<br />
* …
=> Issue #SB-23374 fix: Bulk upload question API URL issue fixes

src/helpers/kafkaUtil.js, src/service/kafkaQumlConsumerService.js
=> Issue #SB-0000 fix: testing kafka issue

src/envVariables.js, src/helpers/kafkaUtil.js, src/service/kafkaQumlConsumerService.js
=> Release 4.5.0

src/service/qumlBulkService.js
<table>
<td>
</td></table>
<br />
* …
=> Issue #SB-23374 fix : question bulk upload status API issue fixes

src/helpers/csv-helper-util.js, src/service/kafkaQumlConsumerService.js
<table>
<td>
</td></table>
<br />
* …
=> Issue #SB-23374 fix : CSV helper util issue fixes

src/service/kafkaQumlConsumerService.js, src/service/qumlBulkService.js
<table>
<td>
</td></table>
<br />
* …
=> Issue #SB-23374 fix : Bulk question link issue fixes

src/service/print/docx.js, src/service/print/getdocxdata.js
text with all styling like _**styling**_ was working, so just displayed plain text .
=> styling issue (combine all styles)- just took plain text

src/models/form_config.js, src/routes/programRoutes.js, src/service/formConfig.js, src/service/messageUtil.js, src/test/service/formConfigSpec.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26390" title="SB-26390" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-26390</a>  Sourcing Project: Framework metadata population - Part 2
</td></table>
<br />
* …
=> Issue #sb-26390 fix: formconfig on program service level

src/helpers/programHelper.js, src/helpers/publishHelper.js, src/helpers/updateHierarchy.helper.js, src/middlewares/request.middleware.js, src/service/print/dataImporter.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25589" title="SB-25589" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-25589</a>  Sourcing: Integration of Collection V4 API's 
</td></table>
<br />
* …
=> Issue #SB-25589 chore: V4 API's integration

src/envVariables.js, src/routes/print.js, src/service/print/dataImporter.js, src/service/print/docx.js, src/service/print/docxHelper.js, src/service/print/getdocxdata.js, src/service/print/printDocxV1.0/dataImporter.js, src/service/print/printDocxV1.0/docx.js, src/test/service/printService.js
Print docx Service for version 1.0 flow
https://project-sunbird.atlassian.net/wiki/spaces/PRD/pages/3033169921/Enabling+Print+Program+Service+for+Refactor+Flow+QuML+1.0
=> Print docx Changes

src/helpers/updateHierarchy.helper.js, src/service/print/docxHelper.js, src/service/print/getdocxdata.js, src/service/print/printDocxV1.0/dataImporter.js, src/service/print/printDocxV1.0/docx.js
=> Issue SB-000 merge: Merge Release 4.6.0 into 4.7.0

src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28212" title="SB-28212" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28212</a>  Upgrade user org APIs V1.0 to V5.0
</td></table>
<br />
* Hardware …
=> Issue #SB-28212 chore: upgrade org v1 to org v2

src/service/print/getdocxdata.js
https://project-sunbird.atlassian.net/browse/SB-28503 
fixed this issue.
=> "Handled no data in MTF table"

src/helpers/updateHierarchy.helper.js, src/service/print/docxHelper.js, src/service/print/getdocxdata.js, src/service/print/printDocxV1.0/dataImporter.js, src/service/print/printDocxV1.0/docx.js
=> Merge release 4.6 PRs

src/service/formConfig.js
=> issue #0 fix: get system level default config

src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-28212" title="SB-28212" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-28212</a>  Upgrade user org APIs V1.0 to V5.0
</td></table>
<br />
* Hardware …
=> Issue #SB-28212 fix: request filter change from  isRootOrg to isTenant

src/service/print/csv.js, src/test/service/printService.js
Jira ID - [SB-28919](https://project-sunbird.atlassian.net/browse/SB-28919)
{"error":""} message is getting displayed on downloading the CSV of exam question set having MCQ questions.
=> Snehar nd/printdocx

src/service/print/csv.js, src/service/programService.js
=> Issue SB-29000: merge Release 4.7.0 into 4.8

README.md
=> Issue #0 fix: update the readme file for installation guide

src/routes/print.js, src/service/print/csv.js
=> Handled Hindi char in the file name.

src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/CO-167" title="CO-167" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />CO-167</a>  Sourcing org tenant cards are not available on the Dock landing Page.
</td></table>
<br />
* Software versions: …
=> Issue #CO-167 fix: Sourcing org tenant cards are not available on the Dock landing Page.

src/helpers/programHelper.js, src/helpers/responseUtil.js, src/middlewares/request.middleware.js, src/service/bulkJobService.js, src/service/programService.js
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/CO-267" title="CO-267" target="_blank"><img alt="Minor-Enhancement" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10310?size=medium" />CO-267</a>  Request traceability with proper logs (Part 2)
</td></table>
<br />
Reverts Sunbird-Ed/program-service#293
=> Revert "Issue #co-267 fix: Request traceability with proper logs"

src/routes/print.js, src/service/print/docxHelper.js, src/service/print/getdocxdata.js, src/service/print/lang/english.json, src/service/print/lang/hindi.json, src/service/print/printDocxV1.0/dataImporter.js, src/service/print/printDocxV1.0/docx.js
=> CO-229 CO-230 Print Preview

src/routes/print.js, src/service/print/docxHelper.js, src/service/print/getdocxdata.js, src/service/print/lang/english.json, src/service/print/lang/hindi.json, src/service/print/printDocxV1.0/dataImporter.js, src/service/print/printDocxV1.0/docx.js
Reverts Sunbird-coKreat/program-service#299
=> Revert "CO-229 CO-230 Print Preview"

src/service/print/csv.js
=> Issue #CO-441 fix: commented out json2csv code as it is not working

src/package-lock.json, src/package.json
=> Issue co-441 fix: module node_rsa not found

src/package-lock.json, src/package.json, src/service/print/csv.js
=> Issue #CO-486

src/package-lock.json, src/package.json, src/service/print/csv.js
Reverts Sunbird-coKreat/program-service#311
=> Revert "Issue #CO-486"

src/service/programService.js
=> Issue #co-496 fix: resmsgid for nomination is null

src/service/programService.js
=> Program name like search added

src/envVariables.js, src/service/programService.js, src/service/registryService.js, src/service/userService.js
=> co-716 issues found during testing

src/service/programService.js
=> co-677 dynamically returning the framework fileds from config

src/helpers/programHelper.js
=> Issue co-677 removed hardcoded framework fields

Dockerfile, src/package.json
=> co-607 upgrade node version to 14

src/service/userService.js
=> co-734 pass username in the eData of the kafka event after user deletion

src/service/programService.js, src/service/userService.js
=> co-737 nomination list API is taking firstName lastName from opensaber

src/envVariables.js, src/service/userService.js
=> Updating kafka topic default value

src/service/userService.js
=> Issue #ED-3385: User detele searh token

src/service/loggerService.js, src/service/programService.js, src/service/userService.js
=> Issue #CO-773: Project publish issue

src/service/programService.js
=> Issue #CO-754: Project Filter and reviewer TOC

src/service/programService.js
=> Issue #CO-773: debug logs

src/helpers/programHelper.js, src/helpers/updateHierarchy.helper.js, src/service/loggerService.js, src/service/programService.js
=> Issue #CO-773: Code commented revert

src/service/programService.js
=> Issue #CO-798: Deleted user filter for manage user search call

src/service/programService.js
=> Issue #CO-798: isdelted parameter added

src/service/userService.js
=> Issue: #CO-800: api call change

src/service/programService.js
=> Issue: #CO-798: if condition update

src/service/userService.js
=> Issue: #CO-800: api call change remove learner

src/service/userService.js
=> Issue: #CO-800: user object modified

src/helpers/programHelper.js, src/service/programService.js
=> Issue #CO-760 Fw user cat issue

src/service/print/printDocxV1.0/dataImporter.js
=> Issue #CO-949: question set api update
